name: 'Cosign Action - Sign'
author: 'EyeCantCU'
description: 'Signs target container'
inputs:
  container:
    description: 'Path to target container to sign'
    required: true
  registry:
    description: 'Registry hosting the target container'
    required: true
  registry-token:
    description: 'Password for container registry'
    required: true
  signing-secret:
    description: 'Private key used to sign target container.'
    required: true
  tags:
    description: 'Tags used by target container'
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.registry-token }}

    - name: Install cosign
      uses: sigstore/cosign-installer@v3.3.0

    # https://github.com/macbre/push-to-ghcr/issues/12
    - name: Lowercase container path
      id: container_case
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ inputs.container }}

    - name: Sign container image
      shell: bash
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.container_case.outputs.lowercase }}@${TAGS}
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ inputs.signing-secret }}
        TAGS: ${{ inputs.tags }}
