name: 'Cosign Action - Sign'
author: 'EyeCantCU'
description: 'Signs target container'
inputs:
  containers:
    description: 'Names of target containers to sign'
    required: true
  registry:
    description: 'Registry where the container resides'
    default: 'ghcr.io/ublue-os'
    required: true
  registry-token:
    description: 'Password for container registry'
    required: true
  signing-secret:
    description: 'Private key used to sign target container.'
    required: true
  tags:
    description: 'Tags used by target container'
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.registry-token }}

    - name: Install cosign
      shell: bash
      run: |
        docker pull cgr.dev/chainguard/cosign:latest
        CONTAINER_ID=$(docker run -d cgr.dev/chainguard/cosign:latest)
        docker cp "${CONTAINER_ID}":/usr/bin/cosign /usr/local/bin/cosign

    - name: Sign container image
      shell: bash
      run: |
        REGISTRY=$(echo ${{ inputs.registry }} | awk '{print tolower($0)}')
        for CONTAINER in $(echo "${CONTAINERS}" | tr "," "\n"); do
          cosign sign -y --key env://COSIGN_PRIVATE_KEY $REGISTRY/${CONTAINER}@${TAGS}
        done
      env:
        CONTAINERS: ${{ inputs.containers }}
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ inputs.signing-secret }}
        TAGS: ${{ inputs.tags }}
