name: 'Cosign Action - Sign'
author: 'EyeCantCU'
description: 'Signs target container'
inputs:
  containers:
    description: 'Names of target containers to sign'
    required: true
  registry:
    description: 'Registry where the container resides'
    default: 'ghcr.io/ublue-os'
    required: true
  registry-token:
    description: 'Password for container registry'
    required: true
  signing-secret:
    description: 'Private key used to sign target container.'
    required: true
  tags:
    description: 'Tags used by target container'
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.registry-token }}

    - name: Install cosign
      uses: sigstore/cosign-installer@v3.3.0

    # https://github.com/macbre/push-to-ghcr/issues/12
    - name: Normalize registry
      id: normalized_registry
      shell: bash
      run: |
        echo ${{ inputs.registry }} | awk '{print tolower($0)}'

    - name: Sign container image
      shell: bash
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.normalized_registry.outputs }}/${CONTAINERS}@${TAGS}
      env:
        CONTAINERS: ${{ inputs.containers }}
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ inputs.signing-secret }}
        TAGS: ${{ inputs.tags }}
