name: 'Cosign Action - Sign'
author: 'EyeCantCU'
description: 'Signs target container'
inputs:
  container:
    description: 'Name of target container to sign'
    required: true
  registry-token:
    description: 'Password for container registry'
    required: true
  signing-secret:
    description: 'Private key used to sign target container.'
    required: true
  registry:
    description: 'Registry where the container resides'
    required: true
  tags:
    description: 'Tags used by target container'
    required: true
runs:
  using: "composite"
  steps:
    - name: Extract registry from container path
      shell: bash
      run: echo "REGISTRY=$(cut -d '/' -f 1 <<< ${{ inputs.container }})" >> $GITHUB_ENV

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.registry-token }}

    - name: Install cosign
      uses: sigstore/cosign-installer@v3.3.0

    # https://github.com/macbre/push-to-ghcr/issues/12
    - name: Lowercase container path
      id: container_path
      shell: bash
      run: |
        echo ${{ inputs.registry }}/${{ inputs.container }} | awk '{print tolower($0)}'

    - name: Sign container image
      shell: bash
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.container_path.outputs }}@${TAGS}
      env:
        COSIGN_EXPERIMENTAL: false
        COSIGN_PRIVATE_KEY: ${{ inputs.signing-secret }}
        TAGS: ${{ inputs.tags }}
