name: 'Cosign Action - Verify'
author: 'EyeCantCU'
description: 'Verifies target container'
inputs:
  cert-identity:
    description: 'The identity certificate'
    required: false
  containers:
    description: 'Names of the target containers to verify'
    required: true
  pubkey:
    description: 'Public key used by target container'
    default: 'https://raw.githubusercontent.com/ublue-os/main/main/cosign.pub'
    required: false
  oidc-issuer:
    description: 'The certificate OIDC issuer'
    required: false
  registry:
    description: 'Registry where the container resides'
    default: 'ghcr.io/ublue-os'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@v3.3.0

    - name: Verify container
      shell: bash
      run: |
        REGISTRY=$(echo ${{ inputs.registry }} | awk '{print tolower($0)}')
        if [[ -n "${{ inputs.cert-identity }}" && -n "${{ inputs.oidc-issuer }}" ]]; then
          for CONTAINER in $(echo "${CONTAINERS}" | tr "," "\n"); do
            cosign verify $REGISTRY/${CONTAINER} --certificate-identity=${{ inputs.cert-identity }} --certificate-oidc-issuer=${{ inputs.oidc-issuer }}
          done
        elif [[ -n "${{ inputs.pubkey }}" ]]; then
          for CONTAINER in $(echo "${CONTAINERS}" | tr "," "\n"); do
            cosign verify --key ${{ inputs.pubkey }} $REGISTRY/${CONTAINER}
          done
        else
          exit 1
        fi
      env:
        CONTAINERS: ${{ inputs.containers }}
        COSIGN_EXPERIMENTAL: false
