name: 'Cosign Action - Verify'
author: 'EyeCantCU'
description: 'Verifies target container'
inputs:
  cert-identity:
    description: 'The identity certificate'
    required: false
  container:
    description: 'Name of the target container to verify'
    required: true
  pubkey:
    description: 'Public key used by target container'
    required: false
  oidc-issuer:
    description: 'The certificate OIDC issuer'
    required: false
  registry:
    description: 'Registry where the container resides'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@v3.3.0

    # https://github.com/macbre/push-to-ghcr/issues/12
    - name: Lowercase container path
      id: container_path
      shell: bash
      run: |
        echo ${{ inputs.registry }}/${{ inputs.container }} | awk '{print tolower($0)}'

    - name: Verify container
      shell: bash
      run: |
        if [[ -n "${{ inputs.pubkey }}" ]]; then
          cosign verify --key ${{ inputs.pubkey }} ${{ steps.container_path.outputs }}
        elif [[ -n "${{ inputs.cert-identity }}" && -n "${{ inputs.oidc-issuer }}" ]]; then
          cosign verify ${{ steps.container_path.outputs }} --certificate-identity=${{ inputs.cert-identity }} --certificate-oidc-issuer=${{ inputs.oidc-issuer }}
        else
          exit 1
        fi
      env:
        COSIGN_EXPERIMENTAL: false
