name: 'Cosign Action - Verify'
author: 'EyeCantCU'
description: 'Verifies target container'
inputs:
  cert-identity:
    description: 'The identity certificate'
    required: false
  containers:
    description: 'Names of the target containers to verify'
    required: true
  fail-silently:
    description: 'Fail without exiting.'
    default: 'false'
    required: false
  pubkey:
    description: 'Public key used by target container'
    default: 'https://raw.githubusercontent.com/ublue-os/main/main/cosign.pub'
    required: false
  oidc-issuer:
    description: 'The certificate OIDC issuer'
    required: false
  registry:
    description: 'Registry where the container resides'
    default: 'ghcr.io/ublue-os'
    required: true
runs:
  using: "composite"
  steps:
    - name: Fetch cosign from Chainguard
      shell: bash
      run: |
        docker pull cgr.dev/chainguard/cosign:latest
        CONTAINER_ID=$(docker run -d cgr.dev/chainguard/cosign:latest)
        docker cp "${CONTAINER_ID}":/usr/bin/cosign /usr/local/bin/cosign

    - name: Validate cosign image signatures
      shell: bash
      run: |
        set -o pipefail
        if ! cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com --certificate-identity=https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main cgr.dev/chainguard/cosign | jq; then
          echo "NOTICE: Failed to verify cosign image signatures."
          exit 1
        fi

    - name: Verify container
      shell: bash
      run: |
        REGISTRY=$(echo ${{ inputs.registry }} | awk '{print tolower($0)}')
        set -o pipefail
        if [[ -n "${{ inputs.cert-identity }}" && -n "${{ inputs.oidc-issuer }}" ]]; then
          for CONTAINER in $(echo "${CONTAINERS}" | tr "," "\n"); do
            if ! cosign verify $REGISTRY/${CONTAINER} --certificate-identity=${{ inputs.cert-identity }} --certificate-oidc-issuer=${{ inputs.oidc-issuer }} | jq; then
              echo "NOTICE: Verification failed. Please ensure your public key is correct."
              if [[ "${{ matrix.fail-silently }}" != 'true' ]]; then
                exit 1
              fi
            fi
          done
        elif [[ -n "${{ inputs.pubkey }}" ]]; then
          for CONTAINER in $(echo "${CONTAINERS}" | tr "," "\n"); do
            if ! cosign verify --key ${{ inputs.pubkey }} $REGISTRY/${CONTAINER} | jq; then
              echo "NOTICE: Verification failed. Please ensure your public key is correct."
              if [[ "${{ matrix.fail-silently }}" != 'true' ]]; then
                exit 1
              fi
            fi
          done
        else
          exit 1
        fi
      env:
        CONTAINERS: ${{ inputs.containers }}
        COSIGN_EXPERIMENTAL: false
